Repository BargheNo/Frontend, pull requests merged in 2025-04, with the labels that each got.

#102 Fix/structure setup
  app/BargheNo.ico
  app/BargheNo.png
  app/BargheNo.svg
  app/favicon - Copy.png
  app/favicon.ico
  app/favicon.png
  app/favicon.svg
  app/layout.tsx
  app/style-showcasing/page.tsx
  components/Auth/Login/Login.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/ui/sonner.tsx
  public/BargheNo.ico
  public/BargheNo.png
  public/BargheNo.svg
  public/icos/file.svg
  public/icos/globe.svg
  public/icos/next.svg
  public/icos/signup.jpg
  public/icos/vercel.svg
  public/icos/window.svg
  src/functions/handleAPIErrors.ts
  src/services/apiHub.tsx
  src/store/slices/userSlice.ts
  src/store/store.ts
  src/store/types.ts
  src/types/userdata.ts
  tailwind.config.js
  tailwind.config.ts
Labels: refactor, setup

#103 Refactor/new order
  app/dashboard/new-order/page.tsx
  app/globals.css
  app/logger/page.tsx
  components/Auth/ForgotPassword/ForgotPassword.tsx
  components/Auth/Login/Corplogin/Corplogin.tsx
  components/Auth/Login/Login.tsx
  components/Auth/ResetPassword/ResetPassword.tsx
  components/Auth/Signup/signup.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/Bids/PlaceBidForm/PlaceBidForm.tsx
  components/CorpDashboard/FilterSection.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/Custom/CustomInput/CustomInput.module.css
  components/Custom/CustomInput/CustomInput.tsx
  components/Custom/CustomTextArea/CustomTextArea.module.css
  components/Custom/CustomTextArea/CustomTextArea.tsx
  components/New-Order/new-order.tsx
  components/New-Order/style.module.css
  components/OrderHistory/OrderHistoryPagination.tsx
  components/ui/dialog.tsx
  components/ui/select.tsx
  lib/noNavbar.ts
  public/signup.jpg
  src/functions/handleAPIErrors.ts
  src/services/apiHub.tsx
  src/services/orderService.tsx
  src/types/OrderrequestType.ts
  src/types/apiHubType.ts
Labels: refactor, UI

#104 Feature/admin panel
  app/Untitled.png
  app/admin-dashboard/blogs/page.tsx
  app/admin-dashboard/dashboard/page.tsx
  app/admin-dashboard/finance/page.tsx
  app/admin-dashboard/layout.tsx
  app/admin-dashboard/manage-requests/page.tsx
  app/admin-dashboard/manage-users/page.tsx
  app/admin-dashboard/news/page.tsx
  app/admin-dashboard/page.tsx
  app/admin-dashboard/support/page.tsx
  app/corpdashboard/layout.tsx
  app/dashboard/my-panels/page.tsx
  app/globals.css
  app/style-showcasing/page.tsx
  components/CorpDashboard/FilterSection.tsx
  components/Header/Header.tsx
  components/IconWithBackground/IconWithBackground.tsx
  components/Navbar/MobileNavbarSlider/MobileNavbarSlider.tsx
  components/New-Order/new-order.tsx
  components/Panel/PanelAside/PanelAside.module.css
  components/Panel/PanelAside/PanelAside.tsx
  components/SignupButton/SignupButton.tsx
  components/admin-dashboard/Blogs/BlogsList/BlogsList.module.css
  components/admin-dashboard/Blogs/BlogsList/BlogsList.tsx
  components/admin-dashboard/Blogs/NewBlog/NewBlog.module.css
  components/admin-dashboard/Blogs/NewBlog/NewBlog.tsx
  components/admin-dashboard/News/NewNews/NewNews.module.css
  components/admin-dashboard/News/NewNews/NewNews.tsx
  components/admin-dashboard/News/NewsList/NewsList.module.css
  components/admin-dashboard/News/NewsList/NewsList.tsx
  components/admin-dashboard/Panels/Panels.module.css
  components/admin-dashboard/Panels/Panels.tsx
  components/admin-dashboard/Tickets/Tickets.module.css
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.module.css
  components/admin-dashboard/Users/Users.tsx
  src/services/apiHub.tsx
  src/types/IconWithBackgroundType.ts
  src/types/PanelAsideTypes.ts
Labels: enhancement, UI

#106 Feature/add pannel
  app/corpdashboard/installed-panels/page.tsx
  app/dashboard/new-order/page.tsx
  components/Add-Panel/add-panel.tsx
  components/Add-Panel/style.module.css
  src/services/addpanelService.tsx
  src/types/addPanelType.ts
Labels: enhancement

#107 fix:chenged the corpid and the addpanel service format
  components/Add-Panel/add-panel.tsx
  src/services/addpanelService.tsx
Labels: bug

#111 Refactor/corporate
  app/admin-dashboard/manage-users/page.tsx
  app/admin-dashboard/manage-users/styles.module.css
  app/globals.css
  app/landing/corp-introduction/page.tsx
  app/register-corp/page.tsx
  components/Auth/RegisterCorp/CertificatesForm/CertificatesForm.module.css
  components/Auth/RegisterCorp/CertificatesForm/CertificatesForm.tsx
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.module.css
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.tsx
  components/Auth/RegisterCorp/CorpInfoForm/CorpInfoForm.module.css
  components/Auth/RegisterCorp/CorpInfoForm/CorpInfoForm.tsx
  components/CorpDashboard/FilterSection.tsx
  components/Custom/CustomInput/CustomInput.tsx
  components/Custom/CustomTextArea/CustomTextArea.tsx
  components/Navbar/DesktopNavbar/DesktopNavbar.tsx
  components/Navbar/MobileNavbar/MobileNavbar.tsx
  components/ui/badge.tsx
  components/ui/card.tsx
  components/ui/form.tsx
  components/ui/label.tsx
  components/ui/tabs.tsx
  package-lock.json
  package.json
  public/images/corplanding/6ec5a885-aaf7-4aaf-8266-6026e76e5701.png
  public/images/corplanding/e90b69d0-953a-4953-876e-8476e28f19db.png
  src/store/preLoader.ts
  src/store/slices/corpSlice.ts
  src/store/store.ts
  src/store/types.ts
  src/types/corpType.ts
Labels: bug, refactor, UI

#121 Fix/sprint3
  components/Add-Panel/add-panel.tsx
  components/Auth/ForgotPassword/ForgotPassword.tsx
  components/Auth/Login/Login.tsx
  components/Auth/Login/LoginButton.tsx
  components/Auth/ResetPassword/ResetPassword.tsx
Labels: UI

#132 Feature/new order modal responsiveness
  .github/workflows/CI.yml
  app/dashboard/new-order/page.tsx
  components/New-Order/new-order.tsx
  components/New-Order/style.module.css
  components/OrderHistory/OrderHistory.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/ui/pagination.tsx
  package-lock.json
  package.json
Labels: enhancement

#134 Feature/installed panel page responsiveness
  app/corpdashboard/installed-panels/page.tsx
  components/Add-Panel/add-panel.tsx
  components/Add-Panel/style.module.css
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/InstalledPanels/InstalledPanels.tsx
  components/New-Order/new-order.tsx
  src/types/installedpanelType.ts
Labels: enhancement

#140 Feature/corp messages
  app/corpdashboard/messages/page.tsx
  components/Messages/corp-message-card.tsx
  components/Messages/corp-message-pagination.tsx
  src/types/corpMessageType.ts
Labels: enhancement

#143 Feature/corp messages responsiveness
  app/corpdashboard/messages/page.tsx
  components/Messages/corp-message-card.tsx
  components/Messages/corp-message-pagination.tsx
Labels: enhancement

#144 Ops/ci
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  cypress.config.ts
  cypress/screenshots/login.cy.ts/Login Form -- fill the login form and show success toast (failed).png
  cypress/screenshots/signup.cy.ts/Signup Form -- fill the signup form and show success toast (failed).png
  cypress_output.log
  package-lock.json
  tsconfig.json
Labels: refactor, devops
