Repository BargheNo/Frontend, pull requests merged in 2025-05, with the labels that each got.

#148 Test/register corporate
  app/landing/corp-introduction/page.tsx
  app/register-corp/loading.tsx
  app/register-corp/page.tsx
  components/Auth/RegisterCorp/AddressesForm/AddressesForm.tsx
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.tsx
  components/Auth/RegisterCorp/CorpInfoForm/CorpInfoForm.tsx
  components/Custom/CustomToast/CustomToast.tsx
  cypress/e2e/registerCorp.cy.ts
  cypress/fixtures/example.png
  package.json
Labels: test

#149 Test/forget password
  components/Auth/ForgotPassword/ForgotPassword.tsx
  components/Auth/Login/Login.tsx
  components/Auth/Login/LoginButton.tsx
  components/Auth/ResetPassword/ResetPassword.tsx
  components/Custom/CustomToast/CustomToast.tsx
  components/phoneVerification/phoneVerification.tsx
  cypress/e2e/forgetPassword.cy.ts
Labels: bug, test

#151 Refactor/register corp responsive
  app/register-corp/page.tsx
  components/Auth/RegisterCorp/AddressesForm/AddressesForm.tsx
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.module.css
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.tsx
  components/Auth/RegisterCorp/CorpInfoForm/CorpInfoForm.tsx
  package-lock.json
  src/services/apiHub.tsx
Labels: refactor, design, UI

#152 Feature/initialize panel test
  components/New-Order/new-order.tsx
  cypress/e2e/newOrder.cy.ts
Labels: test

#154 fix:removed the character limit for password in loginPage
  components/Auth/Login/Login.tsx
Labels: enhancement

#158 Fix/register corporate
  app/register-corp/page.tsx
  components/Auth/RegisterCorp/AddressesForm/AddressesForm.tsx
  components/LoadingSpinner/TransparentLoading.tsx
  components/LoadingSpinner/style.css
  src/types/corpType.ts
Labels: bug, refactor

#159 Feature/complete customer notification page
  components/Messages/message-pagination.tsx
  src/types/notificationTypes.ts
Labels: enhancement

#163 Refactor/boilerplate
  app/dashboard/announcements/page.tsx
  app/dashboard/calculator/page.tsx
  app/dashboard/messages/page.tsx
  app/dashboard/my-panels/[panelId]/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/page.tsx
  app/dashboard/repair-history/page.tsx
  app/dashboard/reports/page.tsx
  app/dashboard/tickets/page.tsx
  app/style-showcasing/page.tsx
  components/Announcement/AnnouncementBox/AnnouncementBox.tsx
  components/Auth/Login/Login.tsx
  components/Auth/Signup/signup.tsx
  components/Custom/CustomToast/CustomToast.tsx
  components/Dashboard/PageContainer/PageContainer.module.css
  components/Dashboard/PageContainer/PageContainer.tsx
  components/Dashboard/Tickets/CustomerTickets.tsx
  components/Header/Header.tsx
  components/LoadingSpinner/TransparentLoading.tsx
  components/Messages/message-pagination.tsx
  components/Messages/style.module.css
  components/New-Order/new-order.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/Panel/PanelCard/PanelCard.module.css
  components/Panel/PanelCard/PanelCard.tsx
  components/Panel/PanelCard/ReportModal.tsx
  components/Repair/Customer/CustomRepairRequest.module.css
  components/Repair/Customer/CustomerRepairRequest.tsx
  package-lock.json
  src/services/apiHub.tsx
Labels: bug, refactor, UI
