Repository BargheNo/Frontend, pull requests merged in 2025-08, with the labels that each got.

#190 Feat/status filtering
  app/admin-dashboard/announcements/page.tsx
  app/admin-dashboard/corp-management/page.tsx
  app/admin-dashboard/layout.tsx
  app/admin-dashboard/manage-requests/page.tsx
  app/admin-dashboard/manage-users/page.tsx
  app/corpdashboard/bids/page.tsx
  app/corpdashboard/installed-panels/page.tsx
  app/corpdashboard/layout.tsx
  app/corpdashboard/maintenances/page.tsx
  app/corpdashboard/requests/page.tsx
  app/corpdashboard/warranties/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/page.tsx
  app/dashboard/profile/page.tsx
  app/dashboard/repair-history/page.tsx
  app/dashboard/tickets/page.tsx
  components/AddComponent/AddComponent.tsx
  components/Announcement/AnnounceAddCard/AnnounceAddCard.tsx
  components/Announcement/AnnounceCard/AnnounceCard.tsx
  components/Announcement/AnnounceView/AnnounceView.tsx
  components/Announcement/AnnouncementBox/AnnouncementBox.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/FilterSection.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/CorpDashboard/Warranties/Warranties.tsx
  components/Header/Header.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/InstalledPanels/InstalledPanels.tsx
  components/Loading/LoadingSpinner/LoadingSpinner.tsx
  components/Messages/message-pagination.tsx
  components/Navbar/DesktopNavbar/Dashboard/Dashboard.tsx
  components/NoRecordFound/NoRecordFound.tsx
  components/OrderHistory/OrderHistory.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/CorpManagement/FilterCorps.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/admin-dashboard/Users/FilterUsers.tsx
  components/admin-dashboard/Users/Users.tsx
  src/constants/navItems.tsx
  src/services/notificationService.tsx
  src/services/orderService.tsx
Labels: enhancement

#192 Feature/blog
  TestResult.txt
  app/admin-dashboard/blogs/[id]/page.tsx
  app/admin-dashboard/blogs/page.tsx
  app/admin-dashboard/layout.tsx
  app/announcements/[id]/page.tsx
  app/corpdashboard/blogs/[id]/page.tsx
  app/corpdashboard/blogs/page.tsx
  app/corpdashboard/layout.tsx
  app/dashboard/blogs/[id]/page.tsx
  app/dashboard/blogs/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/my-panels/[panelId]/page.tsx
  app/globals.css
  app/neoStyles.css
  app/profile/page.tsx
  app/providers.tsx
  components/Announcement/AnnounceCard/AnnounceCard.tsx
  components/Announcement/AnnounceEditCard/AnnounceEditCard.tsx
  components/Announcement/AnnounceEditor/AnnounceEditor.tsx
  components/Announcement/AnnounceView/AnnounceView.tsx
  components/Announcement/AnnouncementBox/AnnouncementBox.tsx
  components/Auth/Login/Login.tsx
  components/Blogs/BlogsList/BlogsList.module.css
  components/Blogs/BlogsList/BlogsList.tsx
  components/Blogs/NewBlog/NewBlog.module.css
  components/Blogs/NewBlog/NewBlog.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/PlaceBidForm/PlaceBidForm.tsx
  components/CorpDashboard/Requests/RequestCard/RequestCard.tsx
  components/Custom/CustomTextArea/CustomTextArea.tsx
  components/Custom/NeuFrame/NeuFrame.tsx
  components/Custom/TextTruncator/TextTruncator.tsx
  components/Footer/Footer.tsx
  components/Landing/AboutUsLanding/AboutUsLanding.tsx
  components/Landing/BargheNoLanding/BargheNoLanding.tsx
  components/Landing/D3Panel/D3Panel.tsx
  components/Landing/Landing.tsx
  components/Landing/NewsLanding/NewsLanding.tsx
  components/Navbar/MobileNavbar/MobileNavbar.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/PanelCard/PanelCard.tsx
  components/admin-dashboard/Panels/Panels.tsx
  components/blog/AddBlog/AddBlog.tsx
  components/blog/AddBlog/AddBlogForm.tsx
  components/blog/BlogCard/BlogCard.tsx
  components/blog/BlogEditor/BlogEditor.tsx
  next.config.ts
  package-lock.json
  package.json
  public/images/panels/clean-energy.jpeg
  public/images/panels/panel-blueprint-2.jpeg
  public/images/panels/panel-blueprint.jpeg
  public/models/D3Panel/scene.bin
  public/models/D3Panel/scene.gltf
  public/models/D3Panel/textures/Material.002_baseColor.png
  public/models/D3Panel/textures/Material.002_metallicRoughness.png
  src/constants/navItems.tsx
  src/types/IconWithBackgroundType.ts
  src/types/blogTypes.ts
  tsconfig.json
Labels: bug, enhancement

#194 Fix/pagination
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/Custom/CustomPagination/CustomPagination.tsx
  components/Repair/Customer/CustomerRepairRequest.tsx
  components/ui/pagination.tsx
Labels: enhancement, refactor

#196 Fix/profile
  components/Auth/ForgotPassword/ForgotPassword.tsx
  components/Auth/Login/Login.tsx
  components/Dialog/SubmitButton/SubmitButton.tsx
  components/Navbar/DesktopNavbar/DesktopNavbar.tsx
  components/Profile/ProfilePage/UserProfile.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/CorpManagement/CorpMnagement.module.css
  components/admin-dashboard/Tickets/Tickets.tsx
  cypress/e2e/forgetPassword.cy.ts
  cypress/e2e/signup.cy.ts
Labels: enhancement, refactor, test

#197 Fix/pagination api changes
  .prettierrc
  app/admin-dashboard/blogs/page.tsx
  app/admin-dashboard/reports/page.tsx
  app/admin-dashboard/roles-and-permissions/page.tsx
  app/admin-dashboard/support/page.tsx
  app/corpdashboard/bids/page.tsx
  app/corpdashboard/blogs/page.tsx
  app/corpdashboard/installed-panels/page.tsx
  app/corpdashboard/layout.tsx
  app/corpdashboard/maintenances/page.tsx
  app/corpdashboard/staff/page.tsx
  app/dashboard/blogs/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/page.tsx
  app/dashboard/profile/page.tsx
  app/dashboard/repair-history/page.tsx
  components/Announcement/AnnounceCard/AnnounceCard.tsx
  components/Announcement/AnnounceView/AnnounceView.tsx
  components/Auth/Login/Login.tsx
  components/Auth/ResetPassword/ResetPassword.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/CorpDashboard/Warranties/Warranties.tsx
  components/Custom/CustomPagination/CustomPagination.tsx
  components/Dashboard/Tickets/CustomerTickets.tsx
  components/FilterSection/FilterSection.tsx
  components/FilterSection/FilterSelect.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/Loading/LoadingSpinner/LoadingSpinner.tsx
  components/Messages/message-pagination.tsx
  components/Navbar/MobileNavbar/MobileNavbar.tsx
  components/New-Order/new-order.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/Profile/ProfilePage/UserProfile.tsx
  components/Repair/Customer/CustomerRepairRequest.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/RolesAndPermissions/CreateRoleModal.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/admin-dashboard/Tickets/Ticket.tsx
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.tsx
  components/blog/AddBlog/AddBlogForm.tsx
  components/blog/BlogCard/BlogCard.tsx
  components/blog/BlogEditor/BlogEditor.tsx
  src/constants/navItems.tsx
  src/functions/handleAPIErrors.ts
  src/types/PaginationTypes.ts
  src/types/blogTypes.ts
Labels: bug, refactor

#199 Fix/user pagination
  app/corpdashboard/blogs/page.tsx
  app/dashboard/blogs/page.tsx
  components/Announcement/AnnounceCard/AnnounceCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/Landing/BargheNoLanding/BargheNoLanding.tsx
  components/admin-dashboard/Users/Users.tsx
  components/blog/BlogCard/BlogCard.tsx
  next.config.ts
Labels: bug

#200 Feat/select corp
  app/corpdashboard/layout.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelAside/PanelAsideItem/PanelAsideItem.tsx
  components/ui/accordion.tsx
  src/store/slices/userSlice.ts
  src/types/PanelAsideTypes.ts
Labels: bug, enhancement

#202 Fix/entity monitoring
  app/admin-dashboard/entity-monitoring/bids/page.tsx
  app/admin-dashboard/entity-monitoring/orders/page.tsx
  app/admin-dashboard/entity-monitoring/orders/style.module.css
  app/corpdashboard/maintenances/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/page.tsx
  app/dashboard/repair-history/page.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/Warranties/Warranties.tsx
  components/Custom/CustomTable/CustomTable.tsx
  components/Dashboard/Tickets/CustomerTickets.tsx
  components/FilterSection/FilterSection.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/NoRecordFound/NoRecordFound.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelAside/PanelAsideItem/PanelAsideItem.tsx
  components/admin-dashboard/RolesAndPermissions/CreateRoleModal.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.tsx
  components/ui/accordion.tsx
  components/ui/alert-dialog.tsx
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  components/ui/table.tsx
  package-lock.json
  package.json
  src/constants/navItems.tsx
  src/services/entityMonitoringOrder.tsx
  src/types/PaginationTypes.ts
Labels: enhancement, refactor

#203 Fix/reports
  app/admin-dashboard/reports/page.tsx
  app/dashboard/repair-history/page.tsx
  app/layout.tsx
  components/Dialog/CancelButton/CancelButton.tsx
  components/FilterSection/FilterSection.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Repair/Customer/CustomerRepairDialog.tsx
  components/Slider/Slider.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/ui/dialog.tsx
Labels: bug, refactor

#205 Feat/role and permission filtering
  app/admin-dashboard/roles-and-permissions/page.tsx
  app/corpdashboard/maintenances/page.tsx
  app/dashboard/repair-history/page.tsx
  components/Repair/Corp/CorpRepairDialog.tsx
  components/admin-dashboard/RolesAndPermissions/CreateRoleModal.tsx
  components/admin-dashboard/RolesAndPermissions/EditRoleModal.tsx
  components/admin-dashboard/RolesAndPermissions/RoleItem.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/ui/command.tsx
  components/ui/dialog.tsx
  components/ui/popover.tsx
  cypress/downloads/downloads.htm
  package-lock.json
  package.json
  src/types/RolesAndPermissions.ts
Labels: bug

#211 Fix/responsive corp dashboard
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/PlaceBidForm/PlaceBidForm.tsx
  components/CorpDashboard/Requests/RequestCard/RequestCard.tsx
  components/CorpDashboard/Warranties/AddWarranty.tsx
  components/CorpDashboard/Warranties/WarrantyCard.tsx
  components/InstalledPanels/InstalledPanels.tsx
  components/Landing/Landing.tsx
  components/Repair/Corp/CorpRepairCard.tsx
Labels: UI

#213 Feat/search
  -Nicholas🖤/log.txt
  app/corpdashboard/maintenances/page.tsx
  app/dashboard/announcements/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/page.tsx
  app/dashboard/repair-history/page.tsx
  components/Announcement/AnnounceView/AnnounceView.tsx
  components/Announcement/AnnouncementBox/AnnouncementBox.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/CorpDashboard/Warranties/Warranties.tsx
  components/Custom/CustomInput/CustomInputNoValidation.tsx
  components/Dashboard/Tickets/CustomerTickets.tsx
  components/FilterSection/FilterSection.tsx
  components/FilterSection/FilterSelect.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/Landing/Landing.tsx
  components/Messages/message-pagination.tsx
  components/OrderHistory/OrderHistory.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/admin-dashboard/Tickets/Ticket.tsx
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.tsx
  log.txt
Labels: enhancement, design

#217 Fix/corp suspend
  app/admin-dashboard/entity-monitoring/orders/page.tsx
  app/admin-dashboard/page.tsx
  components/Announcement/AnnounceCard/AnnounceCard.tsx
  components/Announcement/AnnounceView/AnnounceView.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Requests/RequestCard/RequestCard.tsx
  components/Custom/CustomTable/CustomTable.tsx
  components/FilterSection/FilterSection.tsx
  components/FilterSection/FilterSelect.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelAside/PanelAsideItem/PanelAsideItem.tsx
  components/PanelAside/SwitchCorp/SwitchCorp.tsx
  components/Repair/Corp/CorpRepairDialog.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/RolesAndPermissions/RoleItem.tsx
  components/admin-dashboard/RolesAndPermissions/RolesAndPermissions.tsx
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.tsx
  components/ui/tooltip.tsx
  package-lock.json
  package.json
  public/images/admin-dashboard/panelGuy1.jpg
  public/images/admin-dashboard/panelGuy2.jpg
  public/images/admin-dashboard/panelGuy3.jpg
  public/images/admin-dashboard/panelGuy4.jpg
  public/images/admin-dashboard/panelGuy5.jpg
  src/functions/hasPermission.ts
  src/functions/isAdmin.tsx
  src/types/userdata.ts
Labels: bug, refactor, design

#221 Fix/final review minor issues
  app/dashboard/reports/page.tsx
  app/register-corp/page.tsx
  app/terms-and-conditions/page.tsx
  components/Add-Panel/add-panel.tsx
  components/Auth/RegisterCorp/AddressesForm/AddressesForm.tsx
  components/Auth/RegisterCorp/CertificatesForm/CertificatesForm.tsx
  components/Auth/RegisterCorp/ContactInfoForm/ContactInfoForm.tsx
  components/Auth/RegisterCorp/CorpInfoForm/CorpInfoForm.tsx
  components/Auth/Signup/signup.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/PlaceBidForm/PlaceBidForm.tsx
  components/CorpDashboard/Warranties/WarrantyForm.tsx
  components/Custom/CustomInput/CustomInput.tsx
  components/Entity-Monitoring/Orders/order-card.tsx
  components/Entity-Monitoring/Panels/panel-card.tsx
  components/Navbar/MobileNavbar/MobileNavbar.tsx
  components/New-Order/new-order.tsx
  components/PanelAside/SwitchCorp/SwitchCorp.tsx
  components/admin-dashboard/Tickets/Ticket.tsx
  components/admin-dashboard/Users/Users.tsx
  src/constants/navItems.tsx
  src/functions/hasPermission.ts
  src/store/middleware.ts
  src/store/preLoader.ts
  src/store/slices/corpSlice.ts
  src/types/corpType.ts
Labels: bug, refactor

#222 Fix/responsive admin dashboard
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/RolesAndPermissions/RoleItem.tsx
  components/admin-dashboard/Tickets/Ticket.tsx
  components/admin-dashboard/Tickets/Tickets.tsx
  components/admin-dashboard/Users/Users.tsx
Labels: UI

#224 Fix/corp management
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  src/functions/hasPermission.ts
Labels: bug, design

#225 Fix/customer dashboard items
  app/corpdashboard/installed-panels/page.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/InstalledPanels/add-panel.tsx
  components/InstalledPanels/style.module.css
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/Users/Users.tsx
  src/functions/hasPermission.ts
  src/types/installedpanelType.ts
Labels: bug

#228 Feat/request details
  app/admin-dashboard/entity-monitoring/orders/page.tsx
  app/dashboard/new-order/[id]/page.tsx
  app/globals.css
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/Custom/CustomTextArea/CustomTextArea.module.css
  components/Custom/CustomTextArea/CustomTextArea.tsx
  components/New-Order/new-order.tsx
  components/NewOrderDetails/NewOrderDetails.tsx
  components/NewOrderDetails/styles.module.css
  components/OrderHistory/OrderHistory.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/Panel/PanelAside/PanelAsideItem/PanelAsideItem.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  src/functions/Calculations.ts
  src/types/BidCardTypes.ts
  src/types/OrderhistoryType.ts
Labels: enhancement, refactor

#231 Fix/status colors
  app/globals.css
  components/Auth/Login/Login.tsx
  components/Calculator/Calculator.tsx
  components/CorpDashboard/Bids/BidCard.tsx
  components/CorpDashboard/Warranties/WarrantyDetails.tsx
  components/Navbar/DesktopNavbar/DesktopNavbar.tsx
  components/NewOrderDetails/NewOrderDetails.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/PanelAside/SwitchCorp/SwitchCorp.tsx
  components/Repair/Customer/CustomerRepairCard.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/RolesAndPermissions/EditRoleModal.tsx
  components/admin-dashboard/RolesAndPermissions/RoleItem.tsx
  src/functions/Calculations.ts
  src/services/apiHub.tsx
Labels: enhancement, refactor

#233 Feat/panel monitoring
  app/dashboard/my-panels/[id]/page.tsx
  app/dashboard/my-panels/[panelId]/page.tsx
  app/dashboard/my-panels/page.tsx
  app/dashboard/new-order/[id]/page.tsx
  components/Auth/ForgotPassword/ForgotPassword.tsx
  components/Auth/Login/Login.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/InstalledPanels/InstalledPanels.tsx
  components/InstalledPanels/add-panel.tsx
  components/Landing/Landing.tsx
  components/Navbar/DesktopNavbar/DesktopNavbar.tsx
  components/NewOrderDetails/NewOrderDetails.tsx
  components/NewOrderDetails/OrderBidCard.tsx
  components/OrderHistory/OrderHistory.tsx
  components/Panel/PanelAside/PanelAsideItem/PanelAsideItem.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/Panel/PanelDetails/PanelDetails.tsx
  components/Panel/PanelDetails/styles.module.css
  components/PanelAside/SwitchCorp/SwitchCorp.tsx
  components/WebSocketProvider/WebSocketProvider.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/Reports/Reports.tsx
  components/admin-dashboard/Tickets/Ticket.tsx
  src/hooks/useWebSocket.ts
  src/types/userdata.ts
Labels: enhancement
