Repository BargheNo/Frontend, pull requests merged in 2025-06, with the labels that each got.

#170 Feature/complete customer messages
  components/Dashboard/PageContainer/PageContainer.tsx
  components/Messages/Notfication/NotificationBox/NotificationBox.tsx
  components/Messages/Notfication/NotificationBox/NotificationsDialogFields.tsx
  components/Messages/Notfication/NotificationContent/NotificationContent.tsx
  components/Messages/Notfication/NotificationHeader/NotificationHeader.tsx
  components/Messages/message-pagination.tsx
  components/ui/react-hover-card.tsx
  next.config.ts
  package-lock.json
  package.json
  src/functions/toPersianNumbers.ts
  src/services/notificationService.tsx
  src/types/notificationTypes.ts
Labels: enhancement

#175 Feature/entity monitoring
  app/admin-dashboard/layout.tsx
  app/admin-dashboard/orders/page.tsx
  app/admin-dashboard/orders/style.module.css
  app/admin-dashboard/panels/page.tsx
  app/admin-dashboard/panels/style.module.css
  components/Entity-Monitoring/Orders/order-card.tsx
  components/Entity-Monitoring/Orders/order-pagination.tsx
  components/Entity-Monitoring/Orders/style.module.css
  components/Entity-Monitoring/Panels/panel-card.tsx
  components/Entity-Monitoring/Panels/style.module.css
  components/Messages/message-pagination.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/ui/accordion.tsx
  package.json
  src/constants/navItems.tsx
  src/services/entityMonitoringOrder.tsx
  src/services/entityMonitoringPanel.tsx
  src/types/Entity-Monitoring/orderType.ts
  src/types/Entity-Monitoring/panelType.ts
  src/types/PanelAsideTypes.ts
Labels: enhancement

#178 Feat/my panels
  app/corpdashboard/layout.tsx
  app/dashboard/my-panels/page.tsx
  app/register-corp/page.tsx
  components/Add-Panel/add-panel.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/Messages/Notfication/NotificationBox/NotificationBox.tsx
  components/Messages/message-pagination.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/PanelCard/PanelCard.tsx
  src/functions/handleAPIErrors.ts
  src/services/getInstalledPanelsService.tsx
  src/store/slices/corpSlice.ts
  src/types/PanelCardTypes.ts
  src/types/corpType.ts
Labels: bug, refactor

#180 Fix/select components
  app/admin-dashboard/corp-management/page.tsx
  app/admin-dashboard/manage-users/page.tsx
  components/Add-Panel/add-panel.tsx
  components/Dashboard/PageContainer/PageContainer.tsx
  components/InstalledPanels/InstalldPanelPagination.tsx
  components/New-Order/new-order.tsx
  components/admin-dashboard/CorpManagement/CorpManagement.tsx
  components/admin-dashboard/CorpManagement/FilterCorps.tsx
  components/admin-dashboard/Users/FilterUsers.tsx
  components/admin-dashboard/Users/UserRoleModal.tsx
  components/admin-dashboard/Users/Users.module.css
  components/admin-dashboard/Users/Users.tsx
Labels: refactor
