Repository BargheNo/Frontend, pull requests merged in 2025-03, with the labels that each got.

#21 feature : created login component and added its route
  app/login/page.tsx
  components/Auth/Login/Login.tsx
  components/Auth/Login/login.css
  package-lock.json
  public/images/bg4.jpg
Labels: enhancement

#26 Feature/setup dashboard
  .gitignore
  app/panel/dashboard/page.tsx
  app/panel/layout.tsx
  app/panel/my-panels/page.tsx
  components/PanelAside/PanelAside.tsx
  components/PanelCard/PanelCard.tsx
  package-lock.json
  src/store/preLoader.ts
  styles/global.css
Labels: enhancement

#32 Ops/pr validation
  .github/workflows/CD.yml
  .github/workflows/branch-protection.yml
  Dockerfile
  app/panel/layout.tsx
  components/PanelAside/PanelAside.tsx
  components/PanelCard/PanelCard.tsx
  next.config.ts
  package-lock.json
  package.json
  src/types/PanelAsideTypes.ts
  src/types/PanelCardTypes.ts
Labels: bug

#35 Feature/signup
  app/signup/page.tsx
  app/signup/signup.module.css
  components/CustomInput/CustomInput.module.css
  components/CustomInput/CustomInput.tsx
  components/SignupButton/SignupButton.module.css
  components/SignupButton/SignupButton.tsx
  eslintrc.js
  eslintrc.json
  projectNotRunning.bat
  public/signup.jpg
  tsconfig.json
Labels: enhancement

#42 Feature/panels
  app/panel/layout.tsx
  app/panel/my-panels/[panelId]/page.tsx
  app/panel/my-panels/page.tsx
  components/Panel/LiveChart/LiveChart.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/PanelCard/PanelCard.tsx
  package.json
  src/types/PanelCardTypes.ts
Labels: enhancement

#48 fix: rename panel to dashboard
  app/corpdashboard/bids/page.tsx
  app/corpdashboard/editprofile/page.tsx
  app/corpdashboard/installed-panels/page.tsx
  app/corpdashboard/layout.tsx
  app/corpdashboard/maintenances/page.tsx
  app/corpdashboard/messages/page.tsx
  app/corpdashboard/reports/page.tsx
  app/corpdashboard/requests/page.tsx
  app/corpdashboard/technicians/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/my-panels/[panelId]/page.tsx
  app/dashboard/my-panels/page.tsx
  app/panel/dashboard/page.tsx
  app/panel/layout.tsx
  components/Panel/LiveChart/LiveChart.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelCard/PanelCard.tsx
  package-lock.json
  src/types/PanelAsideTypes.ts
  src/types/PanelCardTypes.ts
Labels: enhancement

#52 Feature/placing new bids
  .github/workflows/CD.yml
  Dockerfile
  app/corpdashboard/requests/page.tsx
  app/dashboard/layout.tsx
  app/dashboard/my-panels/[panelId]/page.tsx
  components/CorpDashboard/Requests/FilterSection.tsx
  components/CorpDashboard/Requests/RequestCard.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/CustomInput/CustomInput.tsx
  components/IconWithBackground/IconWithBackground.tsx
  components/Panel/PanelAside/PanelAside.tsx
  components/Panel/PanelCard/PanelCard.tsx
  components/ui/command.tsx
  components/ui/dialog.tsx
  components/ui/popover.tsx
  components/ui/select.tsx
  package-lock.json
  package.json
  src/services/apiHub.tsx
  src/types/IconWithBackgroundType.ts
  src/types/PanelAsideTypes.ts
  src/types/PanelCardTypes.ts
  src/types/RequestCardTypes.ts
  src/types/apiHubType.ts
Labels: enhancement

#58 Ops/pr validation
  .Dockerignore
  .github/workflows/CD.yml
  Dockerfile
  app/panel/layout.tsx
  components/PanelAside/PanelAside.tsx
  components/PanelCard/PanelCard.tsx
  components/ui/input-otp.tsx
  package-lock.json
  package.json
  src/services/apiHub.tsx
Labels: bug, refactor, devops

#63 Feature/landing
  .github/workflows/CD.yml
  Dockerfile
  app/corpdashboard/page.tsx
  app/dashboard/page.tsx
  app/page.tsx
  components/CorpDashboard/FilterSection.tsx
  components/CorpDashboard/Requests/RequestCard/RequestCard.tsx
  components/CustomInput/CustomInput.tsx
  components/Landing/AboutUsLanding/AboutUsLanding.module.css
  components/Landing/AboutUsLanding/AboutUsLanding.tsx
  components/Landing/AnnouncementsLanding/Announcement/Announcement.module.css
  components/Landing/AnnouncementsLanding/Announcement/Announcement.tsx
  components/Landing/AnnouncementsLanding/AnnouncementsLanding.module.css
  components/Landing/AnnouncementsLanding/AnnouncementsLanding.tsx
  components/Landing/BargheNoLanding/BargheNoLanding.module.css
  components/Landing/BargheNoLanding/BargheNoLanding.tsx
  components/Landing/Landing.module.css
  components/Landing/Landing.tsx
  public/images/Landing/man-solar.png
  public/images/Landing/man-solar.svg
  public/images/Landing/panel.png
  public/images/Landing/woman-solar.png
  public/images/Landing/woman-solar.svg
Labels: enhancement

#66 Feature/corp signup
  app/signup/page.tsx
  components/Auth/Signup/signup.module.css
  components/Auth/Signup/signup.tsx
  components/CustomInput/CustomInput.tsx
  components/ui/sonner.tsx
  package-lock.json
  package.json
  src/services/apiHub.tsx
  src/services/registerService.tsx
Labels: enhancement, refactor

#36 Refactor/login
  components/Auth/Login/Login.tsx
  components/Auth/Login/LoginButton.tsx
  components/Auth/Login/login.module.css
  components/CustomInput/CustomInput.tsx
  src/services/apiHub.tsx
  src/types/apiHubType.ts
Labels: refactor

#67 Feature/new order
  app/dashboard/new-order/page.tsx
  app/dashboard/new-order/style.module.css
  components/CorpDashboard/FilterSection.tsx
  components/CorpDashboard/Requests/RequestCard/RequestCard.tsx
  components/CustomInput/CustomInput.module.css
  components/New-Order/new-order.tsx
  components/New-Order/style.module.css
  components/SignupButton/SignupButton.module.css
  components/SignupButton/SignupButton.tsx
  components/ui/select.tsx
  src/services/orderService.tsx
  src/services/provinceService.tsx
  src/services/registerService.tsx
  src/types/OrderrequestType.ts
  src/types/provinceType.ts
Labels: enhancement

#75 Feature/order history
  app/dashboard/new-order/page.tsx
  components/New-Order/new-order.tsx
  components/OrderHistory/OrderHistory.tsx
  components/OrderHistory/OrderHistoryPagination.tsx
  components/ui/button.tsx
  components/ui/pagination.tsx
  src/services/orderService.tsx
  src/services/provinceService.tsx
  src/services/registerService.tsx
  src/types/OrderhistoryType.ts
Labels: enhancement

#98 Feature/chat UI
  components/Auth/Login/Corplogin/Corplogin.tsx
  components/Auth/Login/Login.tsx
  components/Auth/Signup/signup.module.css
  components/Auth/Signup/signup.tsx
  components/CorpDashboard/Bids/Bids.tsx
  components/CorpDashboard/Bids/PlaceBidForm/PlaceBidForm.tsx
  components/CorpDashboard/Requests/Requests.tsx
  components/CustomInput/CustomInput.module.css
  components/CustomInput/CustomInput.tsx
  src/services/apiHub.tsx
  src/services/orderService.tsx
  src/services/provinceService.tsx
  src/services/registerService.tsx
  src/wrappers/NavbarWrappert/NavbarWrapper.tsx
Labels: enhancement, refactor

#99 Style cleanup
  app/globals.css
  app/style-showcasing/page.tsx
Labels: design
